### ISSUE TITLE
Option suggestion: Setting to disable auto assignment of party member roles 

### ISSUE THREAD

**Issue by jjgyc** [shdwp/xivPartyIcons#11]
![ffxiv_dx11_FTonJyoDi7](https://user-images.githubusercontent.com/80708004/145761702-f36f9221-5204-43fe-9c02-ff4395f61c1a.png)

Currently, this is what appears whenever someone posts a fully text macro in chat, resulting in the screen being flooded for a good 30 seconds or more if the macro is long. An option to disable this function would be much appreciated!

**Comment by shdwp** [comment]
Oof, I've only used macro that used boxed versions of positions so this never happened to me. Will fix in the next version.

**Comment by jjgyc** [comment]
Thank you!

**Comment by shdwp** [comment]
Fixed in the latest update.
