### ISSUE TITLE
Addon hides party icons and hp bars during battle

### ISSUE THREAD

**Issue by pikaliov** [shdwp/xivPartyIcons#12]
Hi, I like this addon, but I have problem: addon hides party icons and hp bars during battle. In settings of ff14 all turns on, and works fine wo addon. Can u explain how to setup addon for enable hp bars and icons/nameplates during battle also?

**Comment by shdwp** [comment]
There are no settings nor logic related to `in battle` condition. There are separate settings for when you are in dungeon, in raid, in alliance raid or in overworld - maybe you've misunderstood those? Another possibility is that some other plugin interferes with nameplates.

**Comment by shdwp** [comment]
Closed due to inactivity.

**Comment by dkolb** [comment]
For me, Simple Tweaks's Smart Nameplates was causing this behavior.  Job Icons and HP bars would disappear when characters entered combat.
