### ISSUE TITLE
Feature request: chat name role colors only

### ISSUE THREAD

**Issue by Araiia** [shdwp/xivPartyIcons#15]
Hi! Great plugin so far.

The job abbreviation/role letters add a fair amount of clutter to the chat window and is more granular than the level of useful information I get out of the chat log, especially at a glance. I would love if you added an option to color the chat names only, without appending any extra characters at all.

**Comment by shdwp** [comment]
Makes sense, I will probably add it to next release.

**Comment by shdwp** [comment]
In the next version.
