### ISSUE TITLE
Giant enemy icons

### ISSUE THREAD

**Issue by steeben** [shdwp/xivPartyIcons#16]
I can't tell if this is a conflict with some other plugin, but the enemy icons are randomly giant.

Here's a screenshot: https://i.imgur.com/Lk1v8L3.png

You can see one enemy has a normal icon, and all the others are giant.

**Comment by shdwp** [comment]
Yeah, that happens to me also, albeit rarely. I've looked into it but haven't found a fix yet, maybe one day I will look into it more seriously.

**Comment by shdwp** [comment]
Probably fixed in the next version.
