### ISSUE TITLE
Small job icon and name with role letters

### ISSUE THREAD

**Issue by dawn-star** [shdwp/xivPartyIcons#18]
I really like the feature to show role letters in raids, but I also like to still see player names and job icons

Would it be possible to somehow get them both?

**Comment by shdwp** [comment]
Somewhat. The thing is with current limitation the size of the font have to be the same for all text. So I can put role names on top of the names but those will be relatively small. I'll see whether its a viable option.

**Comment by shdwp** [comment]
The next version will include new preset, which displays job icon and roles along with the name.
