### ISSUE TITLE
Big job Icon & role number getting clipped

### ISSUE THREAD

**Issue by YuriRestia** [shdwp/xivPartyIcons#19]
Hello there! 
The plugin sure is very useful when playing BLM to quickly know who to use AM on, but there's a problem with the big icon and role number option, the letter and icons get clipped together like this, can you look into it?
![2021-12-18_11-50-13-401_Witch'sMoonForGameplay](https://user-images.githubusercontent.com/32875875/146770118-e9af7d9d-be69-4474-83fa-fe99a3d60c8b.png)

**Comment by shdwp** [comment]
Will fix in the next version.

**Comment by shdwp** [comment]
Fixed in the next version.
