### ISSUE TITLE
Minor DOH/DOL Name coloring bug.

### ISSUE THREAD

**Issue by Merkava2k15** [shdwp/xivPartyIcons#25]
I noticed, what I am assuming, is a bug when Chat name coloring with DOH and DOL jobs. Unlike DOW/DOM jobs the coloring seems to overwrite the ENTIRE chat line, changing it to white regardless what sort of message it is (shout, party, say, etc). I'm assuming this is a bug as this does not happen with DOW and DOM's as those only change the color of the characters name without changing the color of the written text.

A visual example:
![image](https://user-images.githubusercontent.com/48537740/147399459-eb2a4f16-e805-4104-94f1-8e3b3aa61a09.png)
On the above picture both are shouts, the PLD line properly shows the right color while on LTW it turns to white (it's still a shout so both lines should be the same color). This happens on any DOH/DOL job that the plugin applies the color change to.

**Comment by shdwp** [comment]
Can you reproduce it when its your message?

**Comment by Merkava2k15** [comment]
yes, it doesn't matter if its your message or someone else, it happens whenever the plugin detects a person's a DOH or DOL. I'm no coding expert but it seems that whatever code limits the color change to just the name isn't working and is applying the color change to the entire line, even the double dots are changed in color.

The above example is actually me doing a shout on an instanced area.

**Comment by shdwp** [comment]
I can not reproduce this with current version, mayhap it has been fixed?

**Comment by Merkava2k15** [comment]
Yes, it seems to have been fixed with the latest version. \o/
