### ISSUE TITLE
'Show sprout, flower, etc icons in addition to the job icons' don't show w/'Small job icon and name'

### ISSUE THREAD

**Issue by Evolutious** [shdwp/xivPartyIcons#26]
'Show sprout, flower, etc icons in addition to the job icons' are not showing for me when i use the option for "Small job icon and name". Am I doing something wrong or can this be added? I really love your mod and would love to use it over alternatives but i need to have the built-in game icon indicators working along with this. Help me Obi Won, you're my only hope!

**Comment by Evolutious** [comment]
It looks like you are actually replacing/using that status icon for your icon. if that is the case, might need to do some manner of append of your icon instead of a replace so that your icon is just being added to the in-game icon. not sure!

**Comment by shdwp** [comment]
This will be partially mitigated in the next release.
