### ISSUE TITLE
Feature Request: New mode, show 1-8 just as in the party list

### ISSUE THREAD

**Issue by DenL** [shdwp/xivPartyIcons#27]
Suggestion to show a big icon of 1/2.../8 depending on the position in the party list. Bonus if it can be role colored (e.g. tank colored blue, healer green, dps red). Or maybe even with big class icon.

Reason for this request instead of just using big class icon with role number, is that role number doesn't always correspond to the party list order. e.g. Tank 1 on nameplate could be the second tank in the list.

**Comment by shdwp** [comment]
Implemented, in the next version.
