### ISSUE TITLE
Options suggestion

### ISSUE THREAD

**Issue by Ashe-H** [shdwp/xivPartyIcons#3]
Hello Shdwp,

First of all thank you for taking the time to make a plugin similar to jobicons with new features, I was always hoping for JobIcons to add a feature where you can hide player names and show only the icon especially for people streaming and you made that possible. 

After trying xivPartyIcons I realized that few options are missing such as Scaling, Color, and repositioning, are these options going to be added in the futur ?

Thank you

**Comment by shdwp** [comment]
Color - maybe. Other options I see no realistical use for.

**Comment by shdwp** [comment]
Closing as a duplicate of https://github.com/shdwp/xivPartyIcons/issues/4
