### ISSUE TITLE
Feature Request: "Small job icon and name" option should follow the game settings for abbreviations 

### ISSUE THREAD

**Issue by AkiraChisaka** [shdwp/xivPartyIcons#30]
So, my game name is Akira Chisaka, displayed like this in game

![image](https://user-images.githubusercontent.com/47231500/147801584-e9db5428-522d-40f0-be9b-92f1946ce690.png)

Using the "Small job icon and name" option, it forces my full name to be displayed.

![image](https://user-images.githubusercontent.com/47231500/147801599-6dbe1e9e-5bba-4104-bdc0-e32820d1b652.png)

This is a bit annoying when raiding. I hope the "Small job icon and name" will just add the small job icon in front of my name, but keep the name format as it was.

Thanks!

**Comment by elrandir** [comment]
It's not a feature request if it's a bug... the same applies to alliance raid names: only the full names are shown, the game option is not used.

**Comment by shdwp** [comment]
Fixed in the next version.
