### ISSUE TITLE
Feature Request: Offset options

### ISSUE THREAD

**Issue by gucciBane** [shdwp/xivPartyIcons#32]
Hey, thanks so much for picking this addon up.

An option to be able to tweak the offset of icons, as Jobicons could, would be A+. Currently, the icons are showing very close to the name for me.

![image](https://user-images.githubusercontent.com/49180180/147811153-b445a042-8212-4966-89dd-1630f4ca787c.png)

Thanks very much!

**Comment by shdwp** [comment]
I will not add such option since with the delay of nameplate updates it is very frustrating to tweak.
