### ISSUE TITLE
PVP settings

### ISSUE THREAD

**Issue by CrownTheEnd** [shdwp/xivPartyIcons#34]
Is there a way to add pvp only setting for enemies that's split from the general overworld setting? I'd like to have small names and icon for overworld and just big job icons for pvp.

**Comment by gucciBane** [comment]
This would be appreciated.

**Comment by squidmade** [comment]
Closing this since the plugin has since been disabled for PvP 349ba3721c704a58ab87585af60b313f270bfe00
