### ISSUE TITLE
Icon packs option

### ISSUE THREAD

**Issue by shdwp** [shdwp/xivPartyIcons#4]
https://cdn.discordapp.com/attachments/719513457988337724/908327538907025450/unknown.png

**Comment by Lumi92** [comment]
This would be AMAZING, those icons are so clean and easy to see

**Comment by Popata** [comment]
This would be great! We need to be able to tell at a glance what we're looking at. Also maybe the option to resize them?

**Comment by shdwp** [comment]
In the next version.
