### ISSUE TITLE
Feature Request: Support for in-a-party icon, etc.

### ISSUE THREAD

**Issue by Orudeon** [shdwp/xivPartyIcons#40]
Hello! I would love if you added support for icons showing someone's in a party, along with other elective statuses. I've had friends ask to invite people who aren't in a party in Bozja and I've had to explain the plugin doesn't show me that (at least with 'small job icon and name' or 'small job icon, role, and name'; is there another setting that keeps them?).

**Comment by squidmade** [comment]
Now that certain status icons take priority, I can add the icon you're talking about to the list of priority icons. I'm guessing it's the yellow play icon in this screenshot.

![bozja](https://user-images.githubusercontent.com/99750849/198854775-95122efd-e15a-42bc-8aee-43cfc104281c.png)

**Comment by Orudeon** [comment]
Yup! The yellow 'in a duty' icon and  'in a party' or 'party leader' blue flag. Adding those to this plugin would be fantastic!

**Comment by squidmade** [comment]
Sounds good, I'll add the yellow one next time I'm working on the code. With the priority icons update, the in a party and party leader icons are working now.

**Comment by squidmade** [comment]
Implemented as 7d3e69a. It'll be in the next update.
