### ISSUE TITLE
Crashing since latest update 1.0.3.2

### ISSUE THREAD

**Issue by 720mmHowizter** [shdwp/xivPartyIcons#45]
https://i.imgur.com/ia9oBrW.png
Don't know how to check for error logs
Seems to be nameplate related, restarting did nothing.

**Comment by rainbow-shaman** [comment]
Same here restart/ reinstall doesn't work

**Comment by imgidedin** [comment]
Same :(

**Comment by shdwp** [comment]
I think someone from the community fixed this?
