### ISSUE TITLE
[feature request] Option to use JP datacenter role letter conventions (ST and D# instead of OT and M#/R#)

### ISSUE THREAD

**Issue by gnrlpz** [shdwp/xivPartyIcons#5]
Good day, thanks for making this as I personally think it's very useful in the data centers which use raid macros.
I think it would be nice to have an option to swap between what I assume is the EU data center role letter conventions with the Japanese ones so that the plugin is also usable for those who raid in JP:

- OT = ST
- M1/M2 = D1/D2
- R1/R2 = D3/D4
MT and the two healers are the same here.

While it's possible to manually assign using the options you provided in the right-click menu, not being able to auto-assign because of the slightly different role letters somewhat undermines the point of the plugin, so I hope this feature can be considered. Thank you!

**Comment by shdwp** [comment]
Coming in the next update.

Note that context menu options are still named the same, that will be fixed later (require a minor rewrire).
