### ISSUE TITLE
Does not always disable in PvP

### ISSUE THREAD

**Issue by retep998** [shdwp/xivPartyIcons#53]
I've noticed this in Borderland Ruins (Secure) in particular, but it seems like this plugin does not always disable itself in frontlines PvP. In Crystalline Conflict I've had no issues however.

**Comment by retep998** [comment]
Also happened in Fields of Glory (Shatter).

**Comment by Storm3ye** [comment]
After the 6.11 and new update to xivlauncher, its working again.

**Comment by retep998** [comment]
I still saw it occur in Borderland Ruins (Secure) today. I'm pretty sure this is map specific.

**Comment by retep998** [comment]
More recent Dalamud updates seem to have fixed this. I haven't seen this occur on any frontlines map lately.
