### ISSUE TITLE
6.2 update

### ISSUE THREAD

**Issue by Ashe-H** [shdwp/xivPartyIcons#59]
Hello, 

First of all thank you for this Amazing tool, I was just wondering if its gonna be updated for 6.2 or not.

Thanks

**Comment by Windy-blade** [comment]
I miss this tool too, please bring it back!!

**Comment by 720mmHowizter** [comment]
if you look in insights there is a fork by itsanobrainer that is working just fine but you need to compile it, tested it all night raiding yesterday without issues

**Comment by squidmade** [comment]
The update for 6.2 is available in the plugin installer list as of yesterday, please enjoy it.
