### ISSUE TITLE
Summoner/Scholar breaks alliance raid big icon + party number

### ISSUE THREAD

**Issue by mikazuki4649** [shdwp/xivPartyIcons#65]
Only shows up when I'm using scholar or summoner because it treats the pet as a 9th member, breaking the party numbers somehow.

**Comment by squidmade** [comment]
Thanks for reporting this, I'll try and get repro

**Comment by squidmade** [comment]
I have a fix, it'll be in the next update

**Comment by squidmade** [comment]
Fixed in 78c9a5e

**Comment by mikazuki4649** [comment]
Awesome, thanks for the quick fix!
