### ISSUE TITLE
Plugin not found in Dalamud plugin installer

### ISSUE THREAD

**Issue by criccadamus** [shdwp/xivPartyIcons#75]
I'm searching for the plugin in Dalamud, but it doesn't show up when using the terms "icons", "partyicons" or "jobicons" and all the variants I could try.
I also don't see a repo to add to Dalamud so it shows up.

**Comment by Kousuke-kun** [comment]
The PR to D17 hasn't been merged.
goatcorp/DalamudPluginsD17#1065
